all: jarfiles/jacocoagent.jar jarfiles/randoop-all-4.3.2.jar

jarfiles/jacocoagent.jar:
	mkdir jarfiles
	cd jarfiles && wget ...

jarfiles/randoop-all-4.3.2.jar:
	mkdir jarfiles
	cd jarfiles && wget https://github.com/randoop/randoop/releases/download/v4.3.2/randoop-4.3.2.jar
